### ISSUE TITLE
force option

### ISSUE THREAD

**Issue by schnittstabil** [perchten/php-rmrdir#2]
I use `rmrdir` in my tests, however tests may fail and directories are not created, thus a `force` option would be a real benefit over manually catching errors.

**Comment by builtbybrayne** [comment]
Hi @schnittstabil, I'm no longer working in PHP or actively maintaining this repo. I am more than happy to accept pull requests though.

(And I've updated my mail filters so the alerts for this report don't get lost again!).

Regards
Alastair
